// <auto-generated />
using Magazine20056663.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Magazine20056663.Migrations
{
    [DbContext(typeof(Magazine20056663Context))]
    partial class Magazine20056663ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15");

            modelBuilder.Entity("Magazine20056663.ModelClasses.Customer", b =>
                {
                    b.Property<int>("customerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("emailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("familyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("givenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("mobileNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("postalCode")
                        .HasColumnType("TEXT");

                    b.HasKey("customerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Magazine20056663.Pages.MagazineTest.Classes.Magazine", b =>
                {
                    b.Property<int>("magazineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("magazineName")
                        .HasColumnType("TEXT");

                    b.HasKey("magazineID");

                    b.ToTable("Magazine");
                });
#pragma warning restore 612, 618
        }
    }
}
